# Generated by Django 4.1.5 on 2023-02-01 05:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='test_models.passport')),
            ],
        ),
    ]
