# Generated by Django 4.1.5 on 2023-02-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0005_passport_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('student', models.ManyToManyField(to='test_models.student')),
            ],
        ),
    ]
